services:
  - type: web
    name: proyoutubers
    runtime: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "false"
    healthCheckPath: /
